/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fengfl_myapplication_FlJni */

#ifndef _Included_com_example_fengfl_myapplication_FlJni
#define _Included_com_example_fengfl_myapplication_FlJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fengfl_myapplication_FlJni
 * Method:    getHelloWorldStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fengfl_myapplication_FlJni_getHelloWorldStr
  (JNIEnv *, jobject);

/*
 * Class:     com_example_fengfl_myapplication_FlJni
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fengfl_myapplication_FlJni_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_example_fengfl_myapplication_FlJni
 * Method:    sayHaHa
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fengfl_myapplication_FlJni_sayHaHa
  (JNIEnv *, jobject);

/*
 * Class:     com_example_fengfl_myapplication_FlJni
 * Method:    sayHi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fengfl_myapplication_FlJni_sayHi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
